version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 10

    schedule:
      interval: "daily"
      timezone: "Asia/Jakarta"
      time: "07:00"

    assignees:
      - "manferlo81"
